name: 'Setup Python Environment'
description: 'Python環境とuvのセットアップを行う再利用可能なアクション'
inputs:
  python-version:
    description: 'Pythonのバージョン'
    required: false
    default: '3.12'
  install-dependencies:
    description: '依存関係をインストールするか'
    required: false
    default: 'true'
  cache-key:
    description: 'キャッシュキー'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Restore uv cache
      if: inputs.cache-key != ''
      uses: actions/cache@v4
      with:
        path: /tmp/.uv-cache
        key: ${{ inputs.cache-key }}
        restore-keys: |
          uv-${{ runner.os }}-

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: false

    - name: Set up Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: |
        uv sync --dev
        echo "Dependencies installed successfully"
