name: Test

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, develop, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Python ${{ matrix.python-version }} のセットアップ
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: uvのインストール
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-path: |
          pyproject.toml
          uv.lock

    - name: 依存関係のインストール
      run: |
        uv sync --frozen

    - name: Lintの実行
      run: |
        uv run ruff check .

    - name: フォーマットチェック
      run: |
        uv run ruff format . --check

    - name: 型チェックの実行
      run: |
        uv run mypy src/
      continue-on-error: true

    - name: テストの実行
      run: |
        uv run pytest -v --tb=short
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: カバレッジレポートの生成
      run: |
        uv run pytest --cov=src --cov-report=xml --cov-report=term-missing
      continue-on-error: true

    - name: カバレッジレポートのアップロード
      uses: codecov/codecov-action@v5
      with:
        file: ./.pytest_cache/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
      continue-on-error: true

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Python 3.12 のセットアップ
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: uvのインストール
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: 依存関係のインストール
      run: |
        uv sync --frozen

    - name: セキュリティチェックの実行
      run: |
        uv run bandit -r src/ -f txt
      continue-on-error: true
